window.RSL_MORPHOLOGY={
version:'2026-09-14.1',
status:'CURATED_NOT_FULLY_VALIDATED',
entries:{
'писать':{g:'to write / be writing',a:'impf',pair:'написать',view:'writing as process, activity, habit or repetition',parts:[['пис','root'],['а','suffix'],['ть','ending']],affix:'Basic imperfective stem. No productive prefix is being used to create this infinitive.',whole:'Whole-word meaning: write; be engaged in writing.',family:['писать','написать','записать','переписать','подписать','описать'],ex:[['Я пишу письмо.','私は手紙を書いている。'],['Я часто пишу вечером.','私は夕方によく書く。']],c:'Do not infer perfectivity from the absence/presence of one prefix alone.'},
'написать':{g:'to write up / produce a written result',a:'pf',pair:'писать',view:'one writing event viewed as a bounded whole with a resulting text',parts:[['на','prefix'],['пис','root'],['а','suffix'],['ть','ending']],affix:'на- contributes to this derived verb, but it is not a universal “perfective switch.”',whole:'Whole-word meaning: write something as a bounded event; produce the text.',family:['писать','написать','записать','переписать','подписать'],ex:[['Я написал письмо.','私は手紙を書き上げた。'],['Она написала ответ за десять минут.','彼女は10分で返事を書き上げた。']],c:'Aspect comes from the whole lexical verb and context; prefix semantics alone are insufficient.',prefix:'на'},
'записать':{g:'to write down / record',a:'pf',pair:'записывать',view:'one bounded recording/writing-down event',parts:[['за','prefix'],['пис','root'],['а','suffix'],['ть','ending']],affix:'за- is polysemous. Here it participates in the lexicalized sense “record / write down.”',whole:'Whole-word meaning: record, write down, register.',family:['записать','записывать','писать','переписать'],ex:[['Запишите адрес.','住所を書き留めてください。'],['Я записал номер.','私は番号を書き留めた。']],c:'Do not translate за- in isolation and add it mechanically to WRITE.',prefix:'за'},
'записывать':{g:'to write down / record (process, repeated)',a:'impf',pair:'записать',view:'recording as process, repeated or ongoing activity',parts:[['за','prefix'],['пис','root'],['ыва','suffix'],['ть','ending']],affix:'-ывать forms a secondary imperfective in this family; the stem is not just a string equation.',whole:'Whole-word meaning: be recording / record repeatedly.',family:['записать','записывать','писать'],ex:[['Я записываю номер.','私は番号を書き留めている。']],c:'-ывать/-ивать is productive, but not every verb uses it identically.',prefix:'за'},
'переписать':{g:'to rewrite / copy over',a:'pf',pair:'переписывать',view:'one bounded rewrite / transfer event',parts:[['пере','prefix'],['пис','root'],['а','suffix'],['ть','ending']],affix:'пере- often contributes across / over / again; here it supports rewriting/copying over.',whole:'Whole-word meaning: rewrite, copy again or into another form.',family:['писать','переписать','переписывать','перечитать','переделать'],ex:[['Я переписал текст.','私は文章を書き直した。']],c:'пере- can signal repetition, crossing, transfer or excess in other verbs.',prefix:'пере'},
'подписать':{g:'to sign',a:'pf',pair:'подписывать',view:'one bounded signing event',parts:[['под','prefix'],['пис','root'],['а','suffix'],['ть','ending']],affix:'под- historically relates to under/beneath, but this verb is strongly lexicalized.',whole:'Whole-word meaning: sign a document / add a signature.',family:['подписать','подписывать','писать'],ex:[['Подпишите документ здесь.','ここに書類へ署名してください。']],c:'A strong example where whole-word lexical meaning matters more than literal morpheme arithmetic.',prefix:'под'},
'описать':{g:'to describe',a:'pf',pair:'описывать',view:'one bounded act of describing',parts:[['о','prefix'],['пис','root'],['а','suffix'],['ть','ending']],affix:'о-/об- can carry around/about relations in this family.',whole:'Whole-word meaning: describe, represent something in words.',family:['описать','описывать','писать'],ex:[['Опишите ситуацию.','状況を説明してください。']],c:'Modern описать means “describe,” not literally “write around.”',prefix:'о'},
'читать':{g:'to read / be reading',a:'impf',pair:'прочитать',view:'reading as process, activity, habit or repetition',parts:[['чит','root'],['а','suffix'],['ть','ending']],affix:'Basic imperfective reading verb.',whole:'Whole-word meaning: read / be reading.',family:['читать','прочитать','перечитать','дочитать'],ex:[['Я читаю книгу.','私は本を読んでいる。']],c:'Duration or habitual context often invites imperfective, but context is not a keyword formula.'},
'прочитать':{g:'to read through',a:'pf',pair:'читать',view:'reading traversed as a bounded whole',parts:[['про','prefix'],['чит','root'],['а','suffix'],['ть','ending']],affix:'про- contributes a through/across profile here.',whole:'Whole-word meaning: read through a text as one bounded event.',family:['читать','прочитать','перечитать','дочитать'],ex:[['Я прочитал книгу.','私はその本を読み通した。']],c:'про- does not universally mean “finish.”',prefix:'про'},
'делать':{g:'to do / make / be doing',a:'impf',pair:'сделать',view:'doing as activity, process or repeated behavior',parts:[['дел','root'],['а','suffix'],['ть','ending']],affix:'Basic imperfective member of this family.',whole:'Whole-word meaning: do / make.',family:['делать','сделать','переделать','доделать'],ex:[['Что ты делаешь?','何をしているの？']],c:'The aspect pair is lexicalized; do not derive сделать from с- alone.'},
'сделать':{g:'to do / make / get done',a:'pf',pair:'делать',view:'one doing/making event viewed with attained result',parts:[['с','prefix'],['дел','root'],['а','suffix'],['ть','ending']],affix:'с- participates in the historical/derived form; its contribution is not enough to predict the modern meaning.',whole:'Whole-word meaning: do, make, accomplish as a bounded whole.',family:['делать','сделать','переделать','доделать'],ex:[['Я всё сделал.','私は全部やり終えた。']],c:'Highly lexicalized aspect pair: learn the relationship as a whole.',prefix:'с'},
'покупать':{g:'to buy / be buying',a:'impf',pair:'купить',view:'buying as habitual, repeated, general or unfolding activity',parts:[['покупа','stem'],['ть','ending']],affix:'The imperfective stem is not transparently derived by a single productive suffix lesson here.',whole:'Whole-word meaning: buy / be buying.',family:['покупать','купить','покупка','покупатель'],ex:[['Я часто покупаю кофе здесь.','私はここでよくコーヒーを買う。']],c:'This pair shows why “prefix = perfective” is unsafe.'},
'купить':{g:'to buy / acquire once',a:'pf',pair:'покупать',view:'one acquisition packaged as a bounded event',parts:[['куп','root'],['и','suffix'],['ть','ending']],affix:'Different stem shape from покупать; treat as an aspectual word-family correspondence.',whole:'Whole-word meaning: buy, acquire.',family:['купить','покупать','покупка','покупатель'],ex:[['Я купил кофе.','私はコーヒーを買った。']],c:'The contrast is carried by the paired lexical forms, not a simple prefix operation.'},
'говорить':{g:'to speak / talk',a:'impf',pair:'сказать',view:'speech as activity, exchange, process or habit',parts:[['говор','root'],['и','suffix'],['ть','ending']],affix:'No transparent affix operation creates сказать from говорить.',whole:'Whole-word meaning: speak, talk.',family:['говорить','сказать','поговорить','рассказать'],ex:[['Мы долго говорили.','私たちは長い間話していた。']],c:'говорить ↔ сказать is an aspectual/semantic correspondence using different lexical stems.'},
'сказать':{g:'to say / utter',a:'pf',pair:'говорить',view:'one communicative act packaged as a bounded utterance',parts:[['сказ','root'],['а','suffix'],['ть','ending']],affix:'Different lexical stem from говорить.',whole:'Whole-word meaning: say, utter.',family:['сказать','говорить','рассказать','поговорить'],ex:[['Он сказал правду.','彼は真実を言った。']],c:'Do not invent a fake morphological pair rule for говорить → сказать.'},
'вставать':{g:'to get up / be getting up',a:'impf',pair:'встать',view:'getting-up behavior as habitual, repeated or unfolding',parts:[['встава','stem'],['ть','ending']],affix:'Expanded imperfective stem with alternation; segmentation is intentionally cautious.',whole:'Whole-word meaning: get up / rise repeatedly or as process.',family:['вставать','встать','стоять'],ex:[['Я встаю в пять каждое утро.','私は毎朝5時に起きる。']],c:'This family is morphologically richer than “add/remove one affix.”'},
'встать':{g:'to get up / stand up once',a:'pf',pair:'вставать',view:'transition into an upright state as one bounded event',parts:[['в','prefix'],['ст','root/stem'],['а','stem element'],['ть','ending']],affix:'Stem alternation and historical morphology matter; this is a cautious teaching analysis.',whole:'Whole-word meaning: get up / stand up as a bounded transition.',family:['встать','вставать','стоять'],ex:[['Завтра я встану в семь.','明日は7時に起きる。']],c:'Perfective present-looking forms have future reference: встану = I will get up.',prefix:'в'}
},
aliases:{'пишу':'писать','писал':'писать','писала':'писать','написал':'написать','написала':'написать','записал':'записать','переписал':'переписать','подписал':'подписать','описал':'описать','читаю':'читать','читал':'читать','прочитал':'прочитать','делаю':'делать','делал':'делать','сделал':'сделать','покупаю':'покупать','купил':'купить','говорю':'говорить','говорил':'говорить','сказал':'сказать','встаю':'вставать','встал':'встать','встану':'встать'},
common:['писать','написать','записать','переписать','читать','прочитать','делать','сделать','покупать','купить','говорить','сказать','вставать','встать']
};